---
- name: Installing and starting the HTTPD service.
  hosts: all
  become: true
  tasks:
  - name: Insalling httpd service
    yum:
     name: httpd
     state: latest
  - name: Starting the httpd service
    service:
     name: httpd
     state: started
     enabled: true
...
